// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'credit_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CreditDetail _$CreditDetailFromJson(Map<String, dynamic> json) => CreditDetail(
      documentId: json['documentId'] as String,
      createdDT: json['createdDT'] as String,
      reasonId: json['reasonId'] as int,
      documentDate: DateTime.parse(json['documentDate'] as String),
      documentDT: DateTime.parse(json['documentDT'] as String),
      documentSource: json['documentSource'] as String,
      documentReference: json['documentReference'] as String,
      currency: json['currency'] as String,
      totalEx: (json['totalEx'] as num).toDouble(),
      taxAmount: (json['taxAmount'] as num).toDouble(),
      total: (json['total'] as num).toDouble(),
      productPoints: json['productPoints'] as int,
      spendPoints: json['spendPoints'] as int,
      paid: (json['paid'] as num).toDouble(),
      redeemPoints: json['redeemPoints'] as int,
      identityBalance: (json['identityBalance'] as num?)?.toDouble(),
      identityPointBalance: json['identityPointBalance'] as int?,
      identityBonusBalance: json['identityBonusBalance'] as int?,
      balance: (json['balance'] as num).toDouble(),
      pointBalance: json['pointBalance'] as int,
      bonusBalance: json['bonusBalance'] as int,
      allocated: json['allocated'] as bool,
      issuerCompany: json['issuerCompany'] as String,
      issuerCompanyNumber: json['issuerCompanyNumber'] as String,
      issuerStreet: json['issuerStreet'] as String,
      issuerExtended: json['issuerExtended'] as String,
      issuerLocality: json['issuerLocality'] as String,
      issuerRegion: json['issuerRegion'] as String,
      issuerPostalCode: json['issuerPostalCode'] as String,
      issuerCountry: json['issuerCountry'] as String,
      issuerPhoneNumber: json['issuerPhoneNumber'] as String,
      firstName: json['firstName'] as String,
      lastName: json['lastName'] as String,
      company: json['company'] as String,
      companyNumber: json['companyNumber'] as String,
      addressNote: json['addressNote'] as String,
      street: json['street'] as String,
      extended: json['extended'] as String,
      locality: json['locality'] as String,
      region: json['region'] as String,
      postalCode: json['postalCode'] as String,
      country: json['country'] as String,
      phoneNumber: json['phoneNumber'] as String,
      items: (json['items'] as List<dynamic>)
          .map((e) => CreditDetailItem.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$CreditDetailToJson(CreditDetail instance) =>
    <String, dynamic>{
      'documentId': instance.documentId,
      'createdDT': instance.createdDT,
      'reasonId': instance.reasonId,
      'documentDate': instance.documentDate.toIso8601String(),
      'documentDT': instance.documentDT.toIso8601String(),
      'documentSource': instance.documentSource,
      'documentReference': instance.documentReference,
      'currency': instance.currency,
      'totalEx': instance.totalEx,
      'taxAmount': instance.taxAmount,
      'total': instance.total,
      'productPoints': instance.productPoints,
      'spendPoints': instance.spendPoints,
      'paid': instance.paid,
      'redeemPoints': instance.redeemPoints,
      'identityBalance': instance.identityBalance,
      'identityPointBalance': instance.identityPointBalance,
      'identityBonusBalance': instance.identityBonusBalance,
      'balance': instance.balance,
      'pointBalance': instance.pointBalance,
      'bonusBalance': instance.bonusBalance,
      'allocated': instance.allocated,
      'issuerCompany': instance.issuerCompany,
      'issuerCompanyNumber': instance.issuerCompanyNumber,
      'issuerStreet': instance.issuerStreet,
      'issuerExtended': instance.issuerExtended,
      'issuerLocality': instance.issuerLocality,
      'issuerRegion': instance.issuerRegion,
      'issuerPostalCode': instance.issuerPostalCode,
      'issuerCountry': instance.issuerCountry,
      'issuerPhoneNumber': instance.issuerPhoneNumber,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'company': instance.company,
      'companyNumber': instance.companyNumber,
      'addressNote': instance.addressNote,
      'street': instance.street,
      'extended': instance.extended,
      'locality': instance.locality,
      'region': instance.region,
      'postalCode': instance.postalCode,
      'country': instance.country,
      'phoneNumber': instance.phoneNumber,
      'items': instance.items,
    };
