name: single_store_app
description: Free Flow Hub single store app.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.3+50003

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependency_overrides:
#  provider: ^6.0.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  # Annotations
  json_annotation: ^4.4.0
  copy_with_extension_gen: ^4.0.1

  # core
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.11
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  just_audio: ^0.9.18
  equatable: ^2.0.3

  # Widget Helpers
  flex_color_scheme: ^4.1.1
  scrollable_positioned_list: ^0.2.3
  webview_flutter: ^3.0.2
  google_maps_flutter: ^2.1.3
  qr_flutter: ^4.0.0
  flutter_stripe: ^2.4.0
  pay: ^1.0.8
  map_launcher: ^2.2.1+2
  flutter_svg: ^1.0.3
  pinput: ^1.2.2

  # Reactive Forms
  reactive_forms: ^11.0.1
  reactive_dropdown_search: ^0.6.0
  reactive_touch_spin: ^0.4.1
  reactive_segmented_control: ^0.2.0
  reactive_date_time_picker: ^0.2.2

  # Firebase
  firebase_core: ^1.14.0
  #  firebase_crashlytics: ^2.4.4
  firebase_analytics: ^9.1.4
  #  firebase_performance: ^0.8.0+3
  firebase_messaging: ^11.2.12

  # Misc
  clipboard: ^0.1.3

  # Library
  elevated_progress_button:
    path: lib_ffh/elevated_progress_button

  #Preview
  device_preview: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.8.1
  flutter_lints: ^1.0.4

  build_runner: ^2.1.5
  json_serializable: ^6.1.1

  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.5



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons' font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/logo.png
    - assets/sounds/sound1.mp3
    - assets/sounds/sound2.mp3
    - assets/sounds/sound3.mp3
    - assets/sounds/sound4.mp3
    - assets/sounds/sound5.mp3
    - assets/sounds/sound6.mp3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    # While Roboto is included in Android Flutter, it is not available on all platforms
    # to ensure that we get the actual Roboto font on all platform we include it as an asset.
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
